/**
 * Static city dataset for the birthplace picker. Each entry resolves a timezone + longitude that
 * feed engine.ts's buildChart (via internationalBirthToSajuChart), so both fields must be real:
 *   - `timeZone` is a valid IANA zone id (asserted in cities-en.test.ts).
 *   - `longitude` is in degrees, east-positive (negative = West).
 * Weighted toward the US and EU, with Australia/Canada/New Zealand, a few world capitals, and a
 * handful of Korean/Asian cities for the diaspora audience.
 */
export interface City {
  label: string;
  country: string;
  timeZone: string;
  longitude: number;
}

export const CITIES: readonly City[] = [
  // ── United States ──────────────────────────────────────────────
  { label: 'New York, NY', country: 'US', timeZone: 'America/New_York', longitude: -74.006 },
  { label: 'Brooklyn, NY', country: 'US', timeZone: 'America/New_York', longitude: -73.9442 },
  { label: 'Buffalo, NY', country: 'US', timeZone: 'America/New_York', longitude: -78.8784 },
  { label: 'Los Angeles, CA', country: 'US', timeZone: 'America/Los_Angeles', longitude: -118.2437 },
  { label: 'San Diego, CA', country: 'US', timeZone: 'America/Los_Angeles', longitude: -117.1611 },
  { label: 'San Francisco, CA', country: 'US', timeZone: 'America/Los_Angeles', longitude: -122.4194 },
  { label: 'San Jose, CA', country: 'US', timeZone: 'America/Los_Angeles', longitude: -121.8863 },
  { label: 'Sacramento, CA', country: 'US', timeZone: 'America/Los_Angeles', longitude: -121.4944 },
  { label: 'Fresno, CA', country: 'US', timeZone: 'America/Los_Angeles', longitude: -119.7726 },
  { label: 'Oakland, CA', country: 'US', timeZone: 'America/Los_Angeles', longitude: -122.2712 },
  { label: 'Chicago, IL', country: 'US', timeZone: 'America/Chicago', longitude: -87.6298 },
  { label: 'Houston, TX', country: 'US', timeZone: 'America/Chicago', longitude: -95.3698 },
  { label: 'San Antonio, TX', country: 'US', timeZone: 'America/Chicago', longitude: -98.4936 },
  { label: 'Dallas, TX', country: 'US', timeZone: 'America/Chicago', longitude: -96.797 },
  { label: 'Austin, TX', country: 'US', timeZone: 'America/Chicago', longitude: -97.7431 },
  { label: 'Fort Worth, TX', country: 'US', timeZone: 'America/Chicago', longitude: -97.3308 },
  { label: 'El Paso, TX', country: 'US', timeZone: 'America/Denver', longitude: -106.485 },
  { label: 'Phoenix, AZ', country: 'US', timeZone: 'America/Phoenix', longitude: -112.074 },
  { label: 'Tucson, AZ', country: 'US', timeZone: 'America/Phoenix', longitude: -110.9747 },
  { label: 'Mesa, AZ', country: 'US', timeZone: 'America/Phoenix', longitude: -111.8315 },
  { label: 'Philadelphia, PA', country: 'US', timeZone: 'America/New_York', longitude: -75.1652 },
  { label: 'Pittsburgh, PA', country: 'US', timeZone: 'America/New_York', longitude: -79.9959 },
  { label: 'Jacksonville, FL', country: 'US', timeZone: 'America/New_York', longitude: -81.6557 },
  { label: 'Miami, FL', country: 'US', timeZone: 'America/New_York', longitude: -80.1918 },
  { label: 'Tampa, FL', country: 'US', timeZone: 'America/New_York', longitude: -82.4572 },
  { label: 'Orlando, FL', country: 'US', timeZone: 'America/New_York', longitude: -81.3792 },
  { label: 'Columbus, OH', country: 'US', timeZone: 'America/New_York', longitude: -82.9988 },
  { label: 'Cleveland, OH', country: 'US', timeZone: 'America/New_York', longitude: -81.6944 },
  { label: 'Cincinnati, OH', country: 'US', timeZone: 'America/New_York', longitude: -84.512 },
  { label: 'Indianapolis, IN', country: 'US', timeZone: 'America/Indiana/Indianapolis', longitude: -86.1581 },
  { label: 'Charlotte, NC', country: 'US', timeZone: 'America/New_York', longitude: -80.8431 },
  { label: 'Raleigh, NC', country: 'US', timeZone: 'America/New_York', longitude: -78.6382 },
  { label: 'Seattle, WA', country: 'US', timeZone: 'America/Los_Angeles', longitude: -122.3321 },
  { label: 'Spokane, WA', country: 'US', timeZone: 'America/Los_Angeles', longitude: -117.426 },
  { label: 'Denver, CO', country: 'US', timeZone: 'America/Denver', longitude: -104.9903 },
  { label: 'Colorado Springs, CO', country: 'US', timeZone: 'America/Denver', longitude: -104.8214 },
  { label: 'Washington, DC', country: 'US', timeZone: 'America/New_York', longitude: -77.0369 },
  { label: 'Boston, MA', country: 'US', timeZone: 'America/New_York', longitude: -71.0589 },
  { label: 'Nashville, TN', country: 'US', timeZone: 'America/Chicago', longitude: -86.7816 },
  { label: 'Memphis, TN', country: 'US', timeZone: 'America/Chicago', longitude: -90.049 },
  { label: 'Knoxville, TN', country: 'US', timeZone: 'America/New_York', longitude: -83.9207 },
  { label: 'Detroit, MI', country: 'US', timeZone: 'America/Detroit', longitude: -83.0458 },
  { label: 'Grand Rapids, MI', country: 'US', timeZone: 'America/Detroit', longitude: -85.6681 },
  { label: 'Portland, OR', country: 'US', timeZone: 'America/Los_Angeles', longitude: -122.6765 },
  { label: 'Las Vegas, NV', country: 'US', timeZone: 'America/Los_Angeles', longitude: -115.1398 },
  { label: 'Reno, NV', country: 'US', timeZone: 'America/Los_Angeles', longitude: -119.8138 },
  { label: 'Louisville, KY', country: 'US', timeZone: 'America/Kentucky/Louisville', longitude: -85.7585 },
  { label: 'Baltimore, MD', country: 'US', timeZone: 'America/New_York', longitude: -76.6122 },
  { label: 'Milwaukee, WI', country: 'US', timeZone: 'America/Chicago', longitude: -87.9065 },
  { label: 'Madison, WI', country: 'US', timeZone: 'America/Chicago', longitude: -89.4012 },
  { label: 'Albuquerque, NM', country: 'US', timeZone: 'America/Denver', longitude: -106.6504 },
  { label: 'Kansas City, MO', country: 'US', timeZone: 'America/Chicago', longitude: -94.5786 },
  { label: 'St. Louis, MO', country: 'US', timeZone: 'America/Chicago', longitude: -90.1994 },
  { label: 'Atlanta, GA', country: 'US', timeZone: 'America/New_York', longitude: -84.388 },
  { label: 'Savannah, GA', country: 'US', timeZone: 'America/New_York', longitude: -81.0998 },
  { label: 'Omaha, NE', country: 'US', timeZone: 'America/Chicago', longitude: -95.9345 },
  { label: 'New Orleans, LA', country: 'US', timeZone: 'America/Chicago', longitude: -90.0715 },
  { label: 'Baton Rouge, LA', country: 'US', timeZone: 'America/Chicago', longitude: -91.1871 },
  { label: 'Minneapolis, MN', country: 'US', timeZone: 'America/Chicago', longitude: -93.265 },
  { label: 'St. Paul, MN', country: 'US', timeZone: 'America/Chicago', longitude: -93.09 },
  { label: 'Salt Lake City, UT', country: 'US', timeZone: 'America/Denver', longitude: -111.891 },
  { label: 'Boise, ID', country: 'US', timeZone: 'America/Boise', longitude: -116.2023 },
  { label: 'Richmond, VA', country: 'US', timeZone: 'America/New_York', longitude: -77.436 },
  { label: 'Virginia Beach, VA', country: 'US', timeZone: 'America/New_York', longitude: -75.978 },
  { label: 'Oklahoma City, OK', country: 'US', timeZone: 'America/Chicago', longitude: -97.5164 },
  { label: 'Tulsa, OK', country: 'US', timeZone: 'America/Chicago', longitude: -95.9928 },
  { label: 'Birmingham, AL', country: 'US', timeZone: 'America/Chicago', longitude: -86.8025 },
  { label: 'Little Rock, AR', country: 'US', timeZone: 'America/Chicago', longitude: -92.2896 },
  { label: 'Des Moines, IA', country: 'US', timeZone: 'America/Chicago', longitude: -93.6091 },
  { label: 'Wichita, KS', country: 'US', timeZone: 'America/Chicago', longitude: -97.3301 },
  { label: 'Charleston, SC', country: 'US', timeZone: 'America/New_York', longitude: -79.9311 },
  { label: 'Columbia, SC', country: 'US', timeZone: 'America/New_York', longitude: -81.0348 },
  { label: 'Jackson, MS', country: 'US', timeZone: 'America/Chicago', longitude: -90.1848 },
  { label: 'Providence, RI', country: 'US', timeZone: 'America/New_York', longitude: -71.4128 },
  { label: 'Hartford, CT', country: 'US', timeZone: 'America/New_York', longitude: -72.6851 },
  { label: 'Newark, NJ', country: 'US', timeZone: 'America/New_York', longitude: -74.1724 },
  { label: 'Portland, ME', country: 'US', timeZone: 'America/New_York', longitude: -70.2568 },
  { label: 'Manchester, NH', country: 'US', timeZone: 'America/New_York', longitude: -71.4548 },
  { label: 'Burlington, VT', country: 'US', timeZone: 'America/New_York', longitude: -73.2121 },
  { label: 'Wilmington, DE', country: 'US', timeZone: 'America/New_York', longitude: -75.5398 },
  { label: 'Charleston, WV', country: 'US', timeZone: 'America/New_York', longitude: -81.6326 },
  { label: 'Billings, MT', country: 'US', timeZone: 'America/Denver', longitude: -108.5007 },
  { label: 'Fargo, ND', country: 'US', timeZone: 'America/Chicago', longitude: -96.7898 },
  { label: 'Sioux Falls, SD', country: 'US', timeZone: 'America/Chicago', longitude: -96.7003 },
  { label: 'Cheyenne, WY', country: 'US', timeZone: 'America/Denver', longitude: -104.8202 },
  { label: 'Anchorage, AK', country: 'US', timeZone: 'America/Anchorage', longitude: -149.9003 },
  { label: 'Honolulu, HI', country: 'US', timeZone: 'Pacific/Honolulu', longitude: -157.8583 },

  // ── United Kingdom & Ireland ───────────────────────────────────
  { label: 'London, UK', country: 'GB', timeZone: 'Europe/London', longitude: -0.1276 },
  { label: 'Birmingham, UK', country: 'GB', timeZone: 'Europe/London', longitude: -1.8904 },
  { label: 'Manchester, UK', country: 'GB', timeZone: 'Europe/London', longitude: -2.2426 },
  { label: 'Leeds, UK', country: 'GB', timeZone: 'Europe/London', longitude: -1.5491 },
  { label: 'Liverpool, UK', country: 'GB', timeZone: 'Europe/London', longitude: -2.9916 },
  { label: 'Glasgow, UK', country: 'GB', timeZone: 'Europe/London', longitude: -4.2518 },
  { label: 'Edinburgh, UK', country: 'GB', timeZone: 'Europe/London', longitude: -3.1883 },
  { label: 'Bristol, UK', country: 'GB', timeZone: 'Europe/London', longitude: -2.5879 },
  { label: 'Cardiff, UK', country: 'GB', timeZone: 'Europe/London', longitude: -3.1791 },
  { label: 'Belfast, UK', country: 'GB', timeZone: 'Europe/London', longitude: -5.9301 },
  { label: 'Dublin, Ireland', country: 'IE', timeZone: 'Europe/Dublin', longitude: -6.2603 },
  { label: 'Cork, Ireland', country: 'IE', timeZone: 'Europe/Dublin', longitude: -8.4756 },

  // ── Germany ────────────────────────────────────────────────────
  { label: 'Berlin, Germany', country: 'DE', timeZone: 'Europe/Berlin', longitude: 13.405 },
  { label: 'Hamburg, Germany', country: 'DE', timeZone: 'Europe/Berlin', longitude: 9.9937 },
  { label: 'Munich, Germany', country: 'DE', timeZone: 'Europe/Berlin', longitude: 11.582 },
  { label: 'Cologne, Germany', country: 'DE', timeZone: 'Europe/Berlin', longitude: 6.9603 },
  { label: 'Frankfurt, Germany', country: 'DE', timeZone: 'Europe/Berlin', longitude: 8.6821 },
  { label: 'Stuttgart, Germany', country: 'DE', timeZone: 'Europe/Berlin', longitude: 9.1829 },
  { label: 'Düsseldorf, Germany', country: 'DE', timeZone: 'Europe/Berlin', longitude: 6.7735 },
  { label: 'Leipzig, Germany', country: 'DE', timeZone: 'Europe/Berlin', longitude: 12.3731 },

  // ── France ─────────────────────────────────────────────────────
  { label: 'Paris, France', country: 'FR', timeZone: 'Europe/Paris', longitude: 2.3522 },
  { label: 'Marseille, France', country: 'FR', timeZone: 'Europe/Paris', longitude: 5.3698 },
  { label: 'Lyon, France', country: 'FR', timeZone: 'Europe/Paris', longitude: 4.8357 },
  { label: 'Toulouse, France', country: 'FR', timeZone: 'Europe/Paris', longitude: 1.4442 },
  { label: 'Nice, France', country: 'FR', timeZone: 'Europe/Paris', longitude: 7.2619 },
  { label: 'Nantes, France', country: 'FR', timeZone: 'Europe/Paris', longitude: -1.5536 },
  { label: 'Strasbourg, France', country: 'FR', timeZone: 'Europe/Paris', longitude: 7.7521 },
  { label: 'Bordeaux, France', country: 'FR', timeZone: 'Europe/Paris', longitude: -0.5792 },

  // ── Spain ──────────────────────────────────────────────────────
  { label: 'Madrid, Spain', country: 'ES', timeZone: 'Europe/Madrid', longitude: -3.7038 },
  { label: 'Barcelona, Spain', country: 'ES', timeZone: 'Europe/Madrid', longitude: 2.1734 },
  { label: 'Valencia, Spain', country: 'ES', timeZone: 'Europe/Madrid', longitude: -0.3763 },
  { label: 'Seville, Spain', country: 'ES', timeZone: 'Europe/Madrid', longitude: -5.9845 },
  { label: 'Bilbao, Spain', country: 'ES', timeZone: 'Europe/Madrid', longitude: -2.935 },
  { label: 'Málaga, Spain', country: 'ES', timeZone: 'Europe/Madrid', longitude: -4.4214 },
  { label: 'Las Palmas, Spain', country: 'ES', timeZone: 'Atlantic/Canary', longitude: -15.4363 },

  // ── Italy ──────────────────────────────────────────────────────
  { label: 'Rome, Italy', country: 'IT', timeZone: 'Europe/Rome', longitude: 12.4964 },
  { label: 'Milan, Italy', country: 'IT', timeZone: 'Europe/Rome', longitude: 9.19 },
  { label: 'Naples, Italy', country: 'IT', timeZone: 'Europe/Rome', longitude: 14.2681 },
  { label: 'Turin, Italy', country: 'IT', timeZone: 'Europe/Rome', longitude: 7.6869 },
  { label: 'Florence, Italy', country: 'IT', timeZone: 'Europe/Rome', longitude: 11.2558 },
  { label: 'Venice, Italy', country: 'IT', timeZone: 'Europe/Rome', longitude: 12.3155 },
  { label: 'Bologna, Italy', country: 'IT', timeZone: 'Europe/Rome', longitude: 11.3426 },

  // ── Netherlands, Belgium, Switzerland, Austria ─────────────────
  { label: 'Amsterdam, Netherlands', country: 'NL', timeZone: 'Europe/Amsterdam', longitude: 4.9041 },
  { label: 'Rotterdam, Netherlands', country: 'NL', timeZone: 'Europe/Amsterdam', longitude: 4.4777 },
  { label: 'The Hague, Netherlands', country: 'NL', timeZone: 'Europe/Amsterdam', longitude: 4.3007 },
  { label: 'Utrecht, Netherlands', country: 'NL', timeZone: 'Europe/Amsterdam', longitude: 5.1214 },
  { label: 'Brussels, Belgium', country: 'BE', timeZone: 'Europe/Brussels', longitude: 4.3517 },
  { label: 'Antwerp, Belgium', country: 'BE', timeZone: 'Europe/Brussels', longitude: 4.4025 },
  { label: 'Zurich, Switzerland', country: 'CH', timeZone: 'Europe/Zurich', longitude: 8.5417 },
  { label: 'Geneva, Switzerland', country: 'CH', timeZone: 'Europe/Zurich', longitude: 6.1432 },
  { label: 'Bern, Switzerland', country: 'CH', timeZone: 'Europe/Zurich', longitude: 7.4474 },
  { label: 'Vienna, Austria', country: 'AT', timeZone: 'Europe/Vienna', longitude: 16.3738 },
  { label: 'Graz, Austria', country: 'AT', timeZone: 'Europe/Vienna', longitude: 15.4395 },

  // ── Nordics ────────────────────────────────────────────────────
  { label: 'Stockholm, Sweden', country: 'SE', timeZone: 'Europe/Stockholm', longitude: 18.0686 },
  { label: 'Gothenburg, Sweden', country: 'SE', timeZone: 'Europe/Stockholm', longitude: 11.9746 },
  { label: 'Malmö, Sweden', country: 'SE', timeZone: 'Europe/Stockholm', longitude: 13.0038 },
  { label: 'Copenhagen, Denmark', country: 'DK', timeZone: 'Europe/Copenhagen', longitude: 12.5683 },
  { label: 'Oslo, Norway', country: 'NO', timeZone: 'Europe/Oslo', longitude: 10.7522 },
  { label: 'Bergen, Norway', country: 'NO', timeZone: 'Europe/Oslo', longitude: 5.3221 },
  { label: 'Helsinki, Finland', country: 'FI', timeZone: 'Europe/Helsinki', longitude: 24.9384 },
  { label: 'Reykjavik, Iceland', country: 'IS', timeZone: 'Atlantic/Reykjavik', longitude: -21.9426 },

  // ── Poland, Czechia, and other EU ──────────────────────────────
  { label: 'Warsaw, Poland', country: 'PL', timeZone: 'Europe/Warsaw', longitude: 21.0122 },
  { label: 'Kraków, Poland', country: 'PL', timeZone: 'Europe/Warsaw', longitude: 19.945 },
  { label: 'Łódź, Poland', country: 'PL', timeZone: 'Europe/Warsaw', longitude: 19.4560 },
  { label: 'Wrocław, Poland', country: 'PL', timeZone: 'Europe/Warsaw', longitude: 17.0385 },
  { label: 'Prague, Czechia', country: 'CZ', timeZone: 'Europe/Prague', longitude: 14.4378 },
  { label: 'Budapest, Hungary', country: 'HU', timeZone: 'Europe/Budapest', longitude: 19.0402 },
  { label: 'Bucharest, Romania', country: 'RO', timeZone: 'Europe/Bucharest', longitude: 26.1025 },
  { label: 'Lisbon, Portugal', country: 'PT', timeZone: 'Europe/Lisbon', longitude: -9.1393 },
  { label: 'Porto, Portugal', country: 'PT', timeZone: 'Europe/Lisbon', longitude: -8.6291 },
  { label: 'Athens, Greece', country: 'GR', timeZone: 'Europe/Athens', longitude: 23.7275 },
  { label: 'Zagreb, Croatia', country: 'HR', timeZone: 'Europe/Zagreb', longitude: 15.9819 },
  { label: 'Sofia, Bulgaria', country: 'BG', timeZone: 'Europe/Sofia', longitude: 23.3219 },
  { label: 'Bratislava, Slovakia', country: 'SK', timeZone: 'Europe/Bratislava', longitude: 17.1077 },
  { label: 'Ljubljana, Slovenia', country: 'SI', timeZone: 'Europe/Ljubljana', longitude: 14.5058 },
  { label: 'Vilnius, Lithuania', country: 'LT', timeZone: 'Europe/Vilnius', longitude: 25.2797 },
  { label: 'Riga, Latvia', country: 'LV', timeZone: 'Europe/Riga', longitude: 24.1052 },
  { label: 'Tallinn, Estonia', country: 'EE', timeZone: 'Europe/Tallinn', longitude: 24.7536 },
  { label: 'Luxembourg City', country: 'LU', timeZone: 'Europe/Luxembourg', longitude: 6.1296 },

  // ── Canada ─────────────────────────────────────────────────────
  { label: 'Toronto, Canada', country: 'CA', timeZone: 'America/Toronto', longitude: -79.3832 },
  { label: 'Montreal, Canada', country: 'CA', timeZone: 'America/Toronto', longitude: -73.5673 },
  { label: 'Vancouver, Canada', country: 'CA', timeZone: 'America/Vancouver', longitude: -123.1207 },
  { label: 'Calgary, Canada', country: 'CA', timeZone: 'America/Edmonton', longitude: -114.0719 },
  { label: 'Edmonton, Canada', country: 'CA', timeZone: 'America/Edmonton', longitude: -113.4938 },
  { label: 'Ottawa, Canada', country: 'CA', timeZone: 'America/Toronto', longitude: -75.6972 },
  { label: 'Winnipeg, Canada', country: 'CA', timeZone: 'America/Winnipeg', longitude: -97.1384 },
  { label: 'Halifax, Canada', country: 'CA', timeZone: 'America/Halifax', longitude: -63.5752 },
  { label: 'Quebec City, Canada', country: 'CA', timeZone: 'America/Toronto', longitude: -71.2075 },

  // ── Australia & New Zealand ────────────────────────────────────
  { label: 'Sydney, Australia', country: 'AU', timeZone: 'Australia/Sydney', longitude: 151.2093 },
  { label: 'Melbourne, Australia', country: 'AU', timeZone: 'Australia/Melbourne', longitude: 144.9631 },
  { label: 'Brisbane, Australia', country: 'AU', timeZone: 'Australia/Brisbane', longitude: 153.0251 },
  { label: 'Perth, Australia', country: 'AU', timeZone: 'Australia/Perth', longitude: 115.8605 },
  { label: 'Adelaide, Australia', country: 'AU', timeZone: 'Australia/Adelaide', longitude: 138.6007 },
  { label: 'Canberra, Australia', country: 'AU', timeZone: 'Australia/Sydney', longitude: 149.1300 },
  { label: 'Auckland, New Zealand', country: 'NZ', timeZone: 'Pacific/Auckland', longitude: 174.7633 },
  { label: 'Wellington, New Zealand', country: 'NZ', timeZone: 'Pacific/Auckland', longitude: 174.7762 },
  { label: 'Christchurch, New Zealand', country: 'NZ', timeZone: 'Pacific/Auckland', longitude: 172.6362 },

  // ── Korea & other Asian cities (diaspora audience) ─────────────
  { label: 'Seoul, South Korea', country: 'KR', timeZone: 'Asia/Seoul', longitude: 126.978 },
  { label: 'Busan, South Korea', country: 'KR', timeZone: 'Asia/Seoul', longitude: 129.0756 },
  { label: 'Incheon, South Korea', country: 'KR', timeZone: 'Asia/Seoul', longitude: 126.7052 },
  { label: 'Tokyo, Japan', country: 'JP', timeZone: 'Asia/Tokyo', longitude: 139.6917 },
  { label: 'Osaka, Japan', country: 'JP', timeZone: 'Asia/Tokyo', longitude: 135.5023 },
  { label: 'Hong Kong', country: 'HK', timeZone: 'Asia/Hong_Kong', longitude: 114.1694 },
  { label: 'Singapore', country: 'SG', timeZone: 'Asia/Singapore', longitude: 103.8198 },
  { label: 'Shanghai, China', country: 'CN', timeZone: 'Asia/Shanghai', longitude: 121.4737 },
  { label: 'Beijing, China', country: 'CN', timeZone: 'Asia/Shanghai', longitude: 116.4074 },
  { label: 'Taipei, Taiwan', country: 'TW', timeZone: 'Asia/Taipei', longitude: 121.5654 },

  // ── A handful of world capitals ────────────────────────────────
  { label: 'Mexico City, Mexico', country: 'MX', timeZone: 'America/Mexico_City', longitude: -99.1332 },
  { label: 'São Paulo, Brazil', country: 'BR', timeZone: 'America/Sao_Paulo', longitude: -46.6333 },
  { label: 'Buenos Aires, Argentina', country: 'AR', timeZone: 'America/Argentina/Buenos_Aires', longitude: -58.3816 },
  { label: 'Moscow, Russia', country: 'RU', timeZone: 'Europe/Moscow', longitude: 37.6173 },
  { label: 'Istanbul, Turkey', country: 'TR', timeZone: 'Europe/Istanbul', longitude: 28.9784 },
  { label: 'Dubai, UAE', country: 'AE', timeZone: 'Asia/Dubai', longitude: 55.2708 },
  { label: 'Mumbai, India', country: 'IN', timeZone: 'Asia/Kolkata', longitude: 72.8777 },
  { label: 'New Delhi, India', country: 'IN', timeZone: 'Asia/Kolkata', longitude: 77.209 },
  { label: 'Cairo, Egypt', country: 'EG', timeZone: 'Africa/Cairo', longitude: 31.2357 },
  { label: 'Johannesburg, South Africa', country: 'ZA', timeZone: 'Africa/Johannesburg', longitude: 28.0473 },
];

/** Fallback longitude used when a manual (non-picker) entry omits one. 0 = Greenwich meridian. */
export const DEFAULT_LONGITUDE = 0;
